services:
    auth-service:
        build:
            context: .
            dockerfile:  ./auth-service/Dockerfile
        container_name: auth-service
        ports:
        - "5001:5001"
        networks:
        - micro 
    
    order-service:
        build: 
            context: .
            dockerfile: ./order-service/Dockerfile
        container_name: order-service
        ports:
            - "5005:5005"
            - "50055:50055"
        networks:
            - micro
    
    payment-service:
        build:
            context: .
            dockerfile: ./payment-service/Dockerfile
        container_name: payment-service
        ports:
            - "5002:5002"
        networks:
            - micro
    
    product-service:
        build: 
            context: .
            dockerfile: ./product-service/Dockerfile
        container_name: product-service
        ports:
            - "5003:5003"
            - "50058:50058"
        networks:
            - micro
    user-service:
        build: 
            context: .
            dockerfile: ./user-service/Dockerfile
        container_name: user-service
        ports:
            - "5004:5004"
            - "50051:50051"
        networks:
            - micro

networks:
    micro:
        driver: bridge
